"""initial schema

Revision ID: 5c3179978712
Revises: 
Create Date: 2026-10-04 20:13:26.230446

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3179978712'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('office_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('office_name', sa.String(length=255), nullable=False),
    sa.Column('contact_url', sa.String(length=2048), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_routes_category'), 'office_routes', ['category'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('owner_office', sa.String(length=255), nullable=False),
    sa.Column('authority_scope', sa.Text(), nullable=True),
    sa.Column('review_frequency', sa.String(length=100), nullable=False),
    sa.Column('last_reviewed_on', sa.Date(), nullable=False),
    sa.Column('related_source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('source_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('captured_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_or_updated_on', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('CURRENT', 'SUPERSEDED', 'INCOMPLETE', 'UNREVIEWED', name='source_version_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_versions_source_id'), 'source_versions', ['source_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_version_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('locator', sa.String(length=1000), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('embedding', VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_source_version_id'), 'evidence', ['source_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_source_version_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_source_versions_source_id'), table_name='source_versions')
    op.drop_table('source_versions')
    op.drop_table('sources')
    op.drop_index(op.f('ix_office_routes_category'), table_name='office_routes')
    op.drop_table('office_routes')
    # ### end Alembic commands ###
